project:
  title: "Decision making under uncertainty using matrices"
  output-dir: _output
  render:
    - ./docs/l-shaped.qmd
toc: true
number-sections: true
format:
  html:
    html-math-method: katex
    code-fold: true
  pdf:
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm
  revealjs:
    scrollable: true
    smaller: true
    html-math-method: katex
    self-contained-math: true
    chalkboard: true
    auto-stretch: true
    width: 125%
    height: 125%
